function [rw_angular_velocities_derivative__rad_per_s2, ...
            reaction_torque_B_B__N_m, ...
            gyroscopic_torque_B_B__N_m] ...
            = execute(motor_torque_commands__Nm, ...
                        angular_velocity_BI_B__rad_per_s, ...
                        rw_angular_velocities__rad_per_s, ...
                        ParametersRateLimitedReactionWheels)
% execute - Calculate the derivatives of the reaction wheel angular velocities and the reaction and gyroscopic torques
%
%   [rw_angular_velocities_derivative__rad_per_s2, ...
%       reaction_torque_B_B__N_m, ...
%       gyroscopic_torque_B_B__N_m] ...
%       = execute(motor_torque_commands__Nm, ...
%                 angular_velocity_BI_B__rad_per_s, ...
%                 rw_angular_velocities__rad_per_s, ...
%                 ParametersRateLimitedReactionWheels)
%
%   Inputs:
%   motor_torque_commands__Nm: Motor torque commands in N m
%   angular_velocity_BI_B__rad_per_s: Angular velocity in the body frame
%   rw_angular_velocities__rad_per_s: Angular velocities of the reaction wheels in rad/s
%   ParametersRateLimitedReactionWheels: Parameters of the RateLimitedReactionWheels model
%
%   Outputs:
%   rw_angular_velocities_derivative__rad_per_s2: Derivatives of the reaction wheel angular velocities in rad/s^2
%   reaction_torque_B_B__N_m: Reaction torque in the body frame
%   gyroscopic_torque_B_B__N_m: Gyroscopic torque in the body frame
%

%% Abbreviations
% Parameters
max_freqs = ParametersRateLimitedReactionWheels.maximum_frequencies__rad_per_s;
% States
w = rw_angular_velocities__rad_per_s;

for ind = 1:length(max_freqs)
    if abs(w(ind)) >= max_freqs(ind)
        motor_torque_commands__Nm(ind) = 0;
    end
end

%% Output
% call execute method of superclass
[rw_angular_velocities_derivative__rad_per_s2, ...
    reaction_torque_B_B__N_m, ...
    gyroscopic_torque_B_B__N_m] ...
    = execute@GenericReactionWheels(motor_torque_commands__Nm, ...
                                    angular_velocity_BI_B__rad_per_s, ...
                                    w, ...
                                    ParametersRateLimitedReactionWheels);

end